spring.application.name=climalert
# ==========================
# WeatherAPI (se mapea a WeatherApiProperties)
# ==========================
weather-api.base-url=https://api.weatherapi.com/v1
weather-api.key=${WEATHER_API_KEY}
weather-api.location=Buenos Aires

# ==========================
# Umbrales de alerta (se mapea a AlertProperties)
# ==========================
alerta.limite-temperatura=35
alerta.limite-humedad=60
alerta.destinatarios=admin@clima.com,emergencias@clima.com,meteorologia@clima.com

# ==========================
# Mail (Spring lo mapea solo, prefijo estandar spring.mail)
# ==========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8080